name: Test

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main', 'release-*']

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version: ['1.21.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for .codecov.yaml
        id: codecov-enabled
        uses: andstor/file-existence-action@v1
        with:
          files: .codecov.yaml

      - if: steps.codecov-enabled.outputs.files_exists == 'true'
        name: Produce Go Coverage
        run: echo 'COVER_OPTS=-coverprofile=coverage.txt -covermode=atomic' >> $GITHUB_ENV

      - name: Test
        run: go test -race $COVER_OPTS ./...

      - if: steps.codecov-enabled.outputs.files_exists == 'true'
        name: Codecov
        uses: codecov/codecov-action@v1
